
dofile(minetest.get_modpath("mydeck").."/joists.lua")
dofile(minetest.get_modpath("mydeck").."/deckboards.lua")
dofile(minetest.get_modpath("mydeck").."/piles.lua")
dofile(minetest.get_modpath("mydeck").."/rail.lua")
dofile(minetest.get_modpath("mydeck").."/machine.lua")
dofile(minetest.get_modpath("mydeck").."/beam.lua")
dofile(minetest.get_modpath("mydeck").."/stairs.lua")
dofile(minetest.get_modpath("mydeck").."/stain.lua")
dofile(minetest.get_modpath("mydeck").."/lattice.lua")
dofile(minetest.get_modpath("mydeck").."/rail_stained.lua")
dofile(minetest.get_modpath("mydeck").."/deckboards_stained.lua")
dofile(minetest.get_modpath("mydeck").."/piles_stained.lua")
dofile(minetest.get_modpath("mydeck").."/beam_stained.lua")
dofile(minetest.get_modpath("mydeck").."/joists_stained.lua")
dofile(minetest.get_modpath("mydeck").."/stairs_stained.lua")
dofile(minetest.get_modpath("mydeck").."/lattice_stained.lua")
